### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'src/generated/prisma.graphql'

### ISSUE THREAD

**Issue by TheoMer** [zeit/now-examples#201]
So I'm still having a 500 error issue ( https://nodejs-express-1umsmzig1.now.sh/ ), in which the logs state:

```
 [2/4] Fetching packages...
12/19 12:11 PM (34m)
{ Error: ENOENT: no such file or directory, open 'src/generated/prisma.graphql'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at read (/var/task/user/src/index.js:150631:19)
    at Object.importSchema (/var/task/user/src/index.js:150678:15)
    at Object.getCachedTypeDefs (/var/task/user/src/index.js:150597:35)
    at new Prisma (/var/task/user/src/index.js:72096:32)
    at Object.<anonymous> (/var/task/user/src/index.js:93836:12)
    at __webpack_require__ (/var/task/user/src/index.js:21:30)
    at Object.module.exports.Object.assign.i (/var/task/user/src/index.js:95224:12)
    at __webpack_require__ (/var/task/user/src/index.js:21:30)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'src/generated/prisma.graphql' }
12/19 12:11 PM (34m)
Error while initializing entrypoint: { Error: ENOENT: no such file or directory, open 'src/generated/prisma.graphql'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at read (/var/task/user/src/index.js:150631:19)
    at Object.importSchema (/var/task/user/src/index.js:150678:15)
    at Object.getCachedTypeDefs (/var/task/user/src/index.js:150597:35)
    at new Prisma (/var/task/user/src/index.js:72096:32)
    at Object.<anonymous> (/var/task/user/src/index.js:93836:12)
    at __webpack_require__ (/var/task/user/src/index.js:21:30)
    at Object.module.exports.Object.assign.i (/var/task/user/src/index.js:95224:12)
    at __webpack_require__ (/var/task/user/src/index.js:21:30)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'src/generated/prisma.graphql' }
12/19 12:11 PM (34m)
REPORT RequestId: 2ff34126-0387-11e9-a647-e56d8dfdceeb	Duration: 2.63 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 110 MB	
12/19 12:11 PM (34m)
[3/4] Linking dependencies...
12/19 12:11 PM (34m)
[4/4] Building fresh packages...
12/19 12:11 PM (34m)
success Saved lockfile.
12/19 12:11 PM (34m)
Done in 1.49s.
12/19 12:17 PM (28m)
uploading cache (30843 kb) to ad5aa1a547bc763b0623962e65105c6f8b91a4826a1e599365878d18c8012ede...
12/19 12:17 PM (28m)
finished
```

My now.json 
```
{
    "version": 2,
    "name": "nodejs-express",
    "builds": [
        { "src": "src/index.js", "use": "@now/node-server" }
        ...
    ],
    "routes": [
        { "src": "/(.*)", "dest": "src/index.js" }
    ]
}
```

But as can be seen by tha ttached image, the specified document exists in said folder. 

What's the issue here?

![graphql file missing](https://user-images.githubusercontent.com/15969262/50221408-ec85b080-038c-11e9-9960-d3c363303e5e.jpg)

**Comment by TheoMer** [comment]
I'm following the Prisma Playground example ( https://github.com/zeit/now-examples/tree/master/apollo ), which is exactly what my project is.

**Comment by TheoMer** [comment]
Bump!

**Comment by paulogdm** [comment]
Could you try to import it like `__dirname + /src/generated/prisma.graphql`?

**Comment by TheoMer** [comment]
@paulogdm That helped clear up that issue, but other errors relating to *.graphql files occur down the line. 

In the top of my `prisma.graphql` file is specified:

```
# source: https://my-project.herokuapp.com/myproject-production/prod
# timestamp: Mon Dec 17 2018 09:44:12 GMT+0000 (GMT Standard Time)
```

This throws the followivg error in logs:

```
ERROR in /tmp/5b253db6/user/src/generated/prisma.graphql 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> # source: https://my-project.herokuapp.com/myproject-production/prod
| # timestamp: Mon Dec 17 2018 09:44:12 GMT+0000 (GMT Standard Time)
| 
    at compiler.run (/tmp/5b253db6/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:63392:23)
    at finalCallback (/tmp/5b253db6/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:64341:39)
    at hooks.done.callAsync.err (/tmp/5b253db6/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:64357:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/tmp/5b253db6/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:14697:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/tmp/5b253db6/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:14274:20)
    at onCompiled (/tmp/5b253db6/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:64355:21)
    at hooks.afterCompile.callAsync.err (/tmp/5b253db6/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:64683:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/tmp/5b253db6/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:14697:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/tmp/5b253db6/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:14274:20)
    at compilation.seal.err (/tmp/5b253db6/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:64680:30)
01/10 04:16 PM (14m)
patching https://api-bru1.zeit.co/v2/now/deployments/dpl_AFAdSWXsWRZ9MnSX19ZFoh8w76yD/builds/bld_q3w7z9mm6 with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
```

I have zero issues with Now 1.0 building this exact same project.

**Comment by paulogdm** [comment]
Could you try to use our `@now/node-server@canary`?

**Comment by TheoMer** [comment]
@paulogdm In the top of my `schema.graphql` file, if I don't change `# import * from './generated/prisma.graphql'` to `# import * from __dirname + '/generated/prisma.graphql'` I get file can not be located error. But when I do change it i get the following error:

```

Error: Too few regex matches: null
    at parseImportLine (/var/task/user/src/index.js:56468:15)
    at Array.map (<anonymous>)
    at parseSDL (/var/task/user/src/index.js:56490:10)
    at collectDefinitions (/var/task/user/src/index.js:56613:22)
    at Object.importSchema (/var/task/user/src/index.js:56503:14)
    at mergeTypeDefs (/var/task/user/src/index.js:68889:37)
    at new GraphQLServer (/var/task/user/src/index.js:68572:34)
    at createServer (/var/task/user/src/index.js:68458:12)
    at Object.<anonymous> (/var/task/user/src/index.js:67039:16)
    at __webpack_require__ (/var/task/user/src/index.js:21:30)
01/10 04:55 PM (4m)
Error while initializing entrypoint: Error: Too few regex matches: null
    at parseImportLine (/var/task/user/src/index.js:56468:15)
    at Array.map (<anonymous>)
    at parseSDL (/var/task/user/src/index.js:56490:10)
    at collectDefinitions (/var/task/user/src/index.js:56613:22)
    at Object.importSchema (/var/task/user/src/index.js:56503:14)
    at mergeTypeDefs (/var/task/user/src/index.js:68889:37)
    at new GraphQLServer (/var/task/user/src/index.js:68572:34)
    at createServer (/var/task/user/src/index.js:68458:12)
    at Object.<anonymous> (/var/task/user/src/index.js:67039:16)
    at __webpack_require__ (/var/task/user/src/index.js:21:30)
01/10 04:55 PM (4m)
REPORT RequestId: 83f4202c-14f8-11e9-af75-e7cdd415f946	Duration: 5.57 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 114 MB	
01/10 04:55 PM (4m)
Error while initializing entrypoint: Error: Too few regex matches: null
    at parseImportLine (/var/task/user/src/index.js:56468:15)
    at Array.map (<anonymous>)
    at parseSDL (/var/task/user/src/index.js:56490:10)
    at collectDefinitions (/var/task/user/src/index.js:56613:22)
    at Object.importSchema (/var/task/user/src/index.js:56503:14)
    at mergeTypeDefs (/var/task/user/src/index.js:68889:37)
    at new GraphQLServer (/var/task/user/src/index.js:68572:34)
    at createServer (/var/task/user/src/index.js:68458:12)
    at Object.<anonymous> (/var/task/user/src/index.js:67039:16)
    at __webpack_require__ (/var/task/user/src/index.js:21:30)
01/10 04:55 PM (4m)
REPORT RequestId: 89714ec0-14f8-11e9-a1d7-1ba738b7f5e9	Duration: 0.45 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 114 MB	
```

I also get the exact same error locally after making the change to `# import * from __dirname + '/generated/prisma.graphql'`

**Comment by AryanJ-NYC** [comment]
I have a very similar that I described in Spectrum: https://spectrum.chat/?t=171b71eb-c61c-43c8-8739-c15af04c4033

**Comment by degroote22** [comment]
You should not mix graphql imports and js/ts imports.
The syntax on the graphql file will be interpreted by graphql-import and will be ignored by ncc (the compiler which reads the __dirname stuff and move the file to the correct directory etc)

My current setup is to have a 'schema_prep.graphql' that is already preprocessed with the imports from the generated graphql file.
When I'm going to generate the generated file I also run a script that imports it with my custom one and prints the correct one.

Something like this would work:
```typescript
import { importSchema } from "graphql-import";
import * as fs from "fs";

const text = importSchema("./schema.graphql");
fs.writeFileSync("./schema_prep.graphql", text);
```

Later, when building the graphql server you HAVE to use the __dirname in the path.

```typescript
const server = new GraphQLServer({
  typeDefs: __dirname + "/schema_prep.graphql", // using __dirname and importing the merged file
  resolvers: resolvers, // ignore in this example
  context: makeContext, // ignore in this example
});
```

I hope I could make myself clear, but feel free to ask any questions.

**Comment by timothyis** [comment]
Thanks for your reply here @degroote22! @TheoMer did that help at all?

**Comment by TheoMer** [comment]
> When I'm going to generate the generated file I also run a script...
> 
>
> Something like this would work:
> 
> ```ts
> import { importSchema } from "graphql-import";
> import * as fs from "fs";
> 
> const text = importSchema("./schema.graphql");
> fs.writeFileSync("./schema_prep.graphql", text);
> ```

Can you clarify from where/how exactly you are calling this code?

**Comment by degroote22** [comment]
That seems unrelated to the problem.
It seems that prisma-binding is complaining now.
Did you see if the "schema_prep.graphql" file is valid? Was it generated?

I don't know how you automate this step with prisma.yml, just run the script I posted somehow BEFORE running your actual code and check if the preprocessing was done correctly.

**Comment by TheoMer** [comment]
@degroote22 The hook in `prisma.graphql` is being automated from my package.json:

```
  "scripts": {
    ...
    "deploy": "prisma deploy --env-file variables.env"
  },
```

`schema_prep.graphql` is being created but not all of `prisma.graphql` is being copied accross.

**Comment by degroote22** [comment]
That's expected, I guess. It should only copy what you import.
You can automate it like this:
```
    "deploy": "prisma deploy --env-file variables.env && npm run scriptToPreprocess.js"
```

Can you run your code locally with ncc?
Because I couldn't understand your error and it seems to be unrelated to now, maybe you did find a bug in importSchema from 'graphql-import' and then you should look for a fix with them.

If you can provide a full reproduction for the error on a public repository I can help you more.

**Comment by TheoMer** [comment]
@degroote22 I've posted an issue at graphql-import: https://github.com/prisma/graphql-import/issues/289

**Comment by degroote22** [comment]
@TheoMer you're making it hard for people to help you. Consider publishing a repository that reproduces your issue because right now it's hard to know what's going on based on your reports.
You created a bug on graphql-import while the error message comes from prisma-binding.

Almost everytime when I'm going to create a smaller repository that reproduces my bug I end up solving the problem by myself. And if I don't then people can help me.

I don't mean to be harsh or anything but people are just going to ignore the [issue you wrote here.](https://github.com/prisma/graphql-import/issues/289)

**Comment by TheoMer** [comment]
@timothyis Yep, that worked. Many thanks for your assistance on this issue @degroote22

**Comment by timothyis** [comment]
Great to hear @TheoMer! Thank you so much for the help @degroote22.
