### ISSUE TITLE
`next build` or `next start` not working with boiler plate

### ISSUE THREAD

**Issue by crswll** [zeit/now-examples#230]
Steps to replicate:

1. `now init nextjs example`
2. `cd example`
3. `npm install`
4. `npx next build`
5. `npx next start`

Outputs:
```
▴ example npx next start
> Ready on http://undefined:3000
```

Which has this weird **undefined**.

Then when you visit `localhost:3000` it errors out:

```
{ Error: Cannot find module '/Users/joe-user/www/example/.next/server/pages-manifest.json'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at getPagePath (/Users/joe-user/www/example/node_modules/next-server/dist/server/require.js:14:27)
    at Object.requirePage (/Users/joe-user/www/example/node_modules/next-server/dist/server/require.js:30:22)
    at Object.loadComponents (/Users/joe-user/www/example/node_modules/next-server/dist/server/load-components.js:15:34)
    at Server.renderToHTMLWithComponents (/Users/joe-user/www/example/node_modules/next-server/dist/server/next-server.js:194:48)
    at Server.renderToHTML (/Users/joe-user/www/example/node_modules/next-server/dist/server/next-server.js:200:37)
    at Server.render (/Users/joe-user/www/example/node_modules/next-server/dist/server/next-server.js:183:33) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '/Users/joe-user/www/example/.next/server/pages-manifest.json'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at getPagePath (/Users/joe-user/www/example/node_modules/next-server/dist/server/require.js:14:27)
    at Object.requirePage (/Users/joe-user/www/example/node_modules/next-server/dist/server/require.js:30:22)
    at Object.loadComponents (/Users/joe-user/www/example/node_modules/next-server/dist/server/load-components.js:15:34)
    at Server.renderToHTMLWithComponents (/Users/joe-user/www/example/node_modules/next-server/dist/server/next-server.js:194:48)
    at Server.renderErrorToHTML (/Users/joe-user/www/example/node_modules/next-server/dist/server/next-server.js:224:21)
    at Server.renderToHTML (/Users/joe-user/www/example/node_modules/next-server/dist/server/next-server.js:211:29) code: 'MODULE_NOT_FOUND' }
```

**Comment by timothyis** [comment]
Hi @crswll! The latest version of this example uses `target: "serverless"` which works differently from the default Next.js functionality. You can read about this here: https://github.com/zeit/next.js#serverless-deployment

As a side effect, there is no `next start`. If you want to develop locally, you can use `npx next dev` 🙏

**Comment by crswll** [comment]
Beautiful. Thank you for the link! I think I almost google too much when trying to figure this all out and end up in docs using slightly different versions of everything. =)

**Comment by timothyis** [comment]
Sorry for the confusion! This will be better documented very shortly, you just caught it as it's being released 😄

**Comment by crswll** [comment]
It's all good! I appreciate the work.

Should `next export` still work? I ran `next build && next export` but that results in an error.

```
> using build directory: /Users/joe-user/www/xfi-next/.next
  copying "static build" directory
> No "exportPathMap" found in "next.config.js". Generating map from "./pages"
  launching 7 threads with concurrency of 10 per thread
{ Error: Cannot find module '/Users/joe-user/www/xfi-next/.next/server/static/GFlpjxfpInRpjuWJ94ztj/pages/_document'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at loadComponents (/Users/joe-user/www/xfi-next/node_modules/next-server/dist/server/load-components.js:16:24)
    at work (/Users/joe-user/www/xfi-next/node_modules/next/dist/export/worker.js:31:38)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
{ code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
{ Error: Cannot find module '/Users/joe-user/www/xfi-next/.next/server/static/GFlpjxfpInRpjuWJ94ztj/pages/_document'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at loadComponents (/Users/joe-user/www/xfi-next/node_modules/next-server/dist/server/load-components.js:16:24)
    at work (/Users/joe-user/www/xfi-next/node_modules/next/dist/export/worker.js:31:38)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '/Users/joe-user/www/xfi-next/.next/server/static/GFlpjxfpInRpjuWJ94ztj/pages/_document'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at loadComponents (/Users/joe-user/www/xfi-next/node_modules/next-server/dist/server/load-components.js:16:24)
    at work (/Users/joe-user/www/xfi-next/node_modules/next/dist/export/worker.js:31:38)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
```

**Comment by WillowHQ** [comment]
This is still not properly documented. Can we fix this.

**Comment by timothyis** [comment]
@WillowHQ Thanks for pinging. You are right, we need to document our recommended ways of developing using these examples. We are working on improving how these examples are displayed and what information you can use, as we speak.

For now, please look at our guide for local development with Next.js: https://zeit.co/guides/deploying-nextjs-with-now/#step-2:-local-development

**Comment by WillowHQ** [comment]
Can I help, I can update the docs for you ? Bc I want to use next with a server on my local to emulate the environment we will be using it with in production, which is an express server running in K9S.

**Comment by WillowHQ** [comment]
Plus it's just misleading.

**Comment by timothyis** [comment]
I'm confused on what you mean now @WillowHQ. This examples repository is for examples hosted on [Now](https://zeit.co/now). Are you proposing to document hosting elsewhere?
