### ISSUE TITLE
Typescript example error on deploy (Cannot find module 'typescript')

### ISSUE THREAD

**Issue by pie6k** [zeit/now-examples#276]
Reproduce - 

clone this repo
`cd now-examples-master/typescript`

`now`

result:

```
> Deploying ~/Downloads/now-examples-master/typescript under AAAAAA
> Using project typescript
> https://typescript-pjwccz2ky.now.sh [v2] [in clipboard] [4s]
╶ src/frontend/index.ts                    Error               [31s]
╶ src/backend/all/index.ts                 Error               [31s]
╶ src/backend/get-sushi/getSushi.ts        Error               [31s]
╶ src/backend/get-sushi/index.ts           Error               [31s]
╶ src/frontend/layout.ts                   Error               [31s]
╶ src/frontend/sushi/index.ts              Error               [31s]
> Error! 6 build failures occured.
> Error! Check your logs at https://typescript-pjwccz2ky.now.sh/_logs or run `now logs typescript-pjwccz2ky.now.sh`.
```

Logs result:

```
Error: Hash: c13461321b86fc87ae12
Version: webpack 5.0.0-alpha.0
Time: 205ms
Built at: 2019-02-22 19:12:48
   Asset      Size  Chunks  Chunk Names
index.js  2.15 KiB   {404}  main
Entrypoint main = index.js
[992] /tmp/457ecc4a/user/src/frontend/index.ts 964 bytes {404} [built] [failed] [1 error]

ERROR in /tmp/457ecc4a/user/src/frontend/index.ts
Module build failed (from (webpack)/ncc/loaders/ts-loader.js):
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/457ecc4a/ncc/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:194100)
    at __webpack_require__ (/tmp/457ecc4a/ncc/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:216)
    at Object.<anonymous> (/tmp/457ecc4a/ncc/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:113665)
    at __webpack_require__ (/tmp/457ecc4a/ncc/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:216)
    at Object.<anonymous> (/tmp/457ecc4a/ncc/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:210066)
    at __webpack_require__ (/tmp/457ecc4a/ncc/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:216)

    at compiler.close.n (/tmp/457ecc4a/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:1:399469)
    at _promise0.then._result0 (eval at create (/tmp/457ecc4a/ncc/node_modules/@zeit/ncc/dist/ncc/index.js:1:1105949), <anonymous>:13:1)
    at <anonymous>
```

Expected result

Being able to deploy example straight from official examples.

## Note abut node@canary

It works with  `node@canary`, but if I add typescript `paths` it's also broken - check reproduction repo:  https://github.com/pie6k/zeit-now-typescript-broken-example

**Comment by alexbudure** [comment]
Try using the builder "@now/node@canary" instead, that worked for me

**Comment by pie6k** [comment]
It's not working with canary too - I've created reproduction repo

https://github.com/pie6k/zeit-now-typescript-broken-example

Seems it's breaking when I'm using typescript `paths` in `tsconfig.json`

**Comment by timothyis** [comment]
@pie6k would you be able to try again please? 🙏

**Comment by msweeneydev** [comment]
Hey @pie6k, we have now removed this example in favour of one that does not require configuration, therefore I will close this issue.

If you would like to look at the new example, you can do so [here](https://github.com/zeit/now-examples/tree/master/create-react-app-functions).
