### ISSUE TITLE
Error: Cannot find module 'react'

### ISSUE THREAD

**Issue by mozgbrasil** [zeit/now-examples#380]
Hello good Morning

I did the git clone of the repository 

https://github.com/zeit/now-examples

then I executed the command 

    now dev --debug

but the mentioned errors are being returned

    Error: Cannot find module 'react'
        at Function.Module._resolveFilename (module.js:547:15)

then I executed the command 

  CTRL+C

then I executed the command 

  now dev --debug

and the following return was displayed

    The react-scripts package provided by Create React App requires a dependency:

      "babel-loader": "8.0.4"

    Don't try to install it manually: your package manager does it automatically.
    However, a different version of babel-loader was detected higher up in the tree:

      /home/marcio/dados/mozgbrasil/zeit-now/node_modules/babel-loader (version: 7.1.5) 

then I executed the command 

      $ npm ls babel-loader
      /home/marcio/dados/mozgbrasil/zeit-now
      └─┬ mdx-deck@1.7.15
        └── babel-loader@7.1.5 

I see that the package.json file was created in the root directory with only this requirement

--

Doing another test, on the python folder, see the result

--

    /zeit-now/python$ now dev --debug
    > [debug] [2019-05-29T20:12:22.705Z] Found config in file /home/marcio/dados/mozgbrasil/zeit-now/python/now.json
    > [debug] [2019-05-29T20:12:22.711Z] Using Now CLI 15.3.0
    > [debug] [2019-05-29T20:12:22.712Z] user supplied known subcommand
    > Now CLI 15.3.0 dev (beta) — https://zeit.co/feedback/dev
    > [debug] [2019-05-29T20:12:22.761Z] The yarn executable is already cached, not re-downloading
    > [debug] [2019-05-29T20:12:22.761Z] Reading `now.json` file
    > [debug] [2019-05-29T20:12:22.764Z] Locating files /home/marcio/dados/mozgbrasil/zeit-now/python
    > [debug] [2019-05-29T20:12:22.765Z] Ignoring /home/marcio/dados/mozgbrasil/zeit-now/python/.now
    > [debug] [2019-05-29T20:12:22.766Z] Ignoring /home/marcio/dados/mozgbrasil/zeit-now/python/README.md
    > [debug] [2019-05-29T20:12:22.767Z] Locating files /home/marcio/dados/mozgbrasil/zeit-now/python: 1.862ms
    > [debug] [2019-05-29T20:12:55.632Z] Locating files /home/marcio/dados/mozgbrasil/zeit-now/python
    > [debug] [2019-05-29T20:12:55.632Z] Locating files /home/marcio/dados/mozgbrasil/zeit-now/python: 0.053ms
    > [debug] [2019-05-29T20:12:55.717Z] Adding build match for "index.py"
    > Ready! Available at http://localhost:3000
    > GET /
    > [debug] [2019-05-29T20:13:00.178Z] Locating files /home/marcio/dados/mozgbrasil/zeit-now/python
    > [debug] [2019-05-29T20:13:00.178Z] Locating files /home/marcio/dados/mozgbrasil/zeit-now/python: 0.054ms
    > [debug] [2019-05-29T20:13:00.180Z] Building asset "index.py-" for "GET /"
    > Building @now/python:index.py
    > [debug] [2019-05-29T20:13:00.181Z] Using `@now/python@0.2.4`
    > [debug] [2019-05-29T20:13:00.181Z] Creating build process for index.py
    downloading files...
    running "pip install --target . --upgrade werkzeug"...
    Collecting werkzeug
      Using cached https://files.pythonhosted.org/packages/9f/57/92a497e38161ce40606c27a86759c6b92dd34fcdb33f64171ec559257c02/Werkzeug-0.15.4-py2.py3-none-any.whl
    Installing collected packages: werkzeug
    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
        prefix=options.prefix_path,
      File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
        self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
      File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
        isolated=self.isolated,
      File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
        prefix=prefix,
      File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
        i.finalize_options()
      File "/usr/lib/python3.6/distutils/command/install.py", line 274, in finalize_options
        raise DistutilsOptionError("can't combine user with prefix, "
    distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
    failed to run "pip install --target . --upgrade werkzeug"...
    > [debug] [2019-05-29T20:13:01.668Z] Built asset index.py-
    { Error: Command failed: pip3 install --target . --upgrade werkzeug
        at makeError (/home/marcio/.cache/co.zeit.now/dev/builders/node_modules/execa/index.js:174:9)
        at Promise.all.then.arr (/home/marcio/.cache/co.zeit.now/dev/builders/node_modules/execa/index.js:278:16)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
      message: 'Command failed: pip3 install --target . --upgrade werkzeug',
      code: 2,
      stdout: null,
      stderr: null,
      failed: true,
      signal: null,
      cmd: 'pip3 install --target . --upgrade werkzeug',
      timedOut: false,
      killed: false }
    > [debug] [2019-05-29T20:13:01.673Z] Error: Command failed: pip3 install --target . --upgrade werkzeug
        at makeError (/home/marcio/.cache/co.zeit.now/dev/builders/node_modules/execa/index.js:174:9)
        at Promise.all.then.arr (/home/marcio/.cache/co.zeit.now/dev/builders/node_modules/execa/index.js:278:16)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
    > [debug] [2019-05-29T20:13:01.675Z] Build process for index.py exited with 1
    ^C
    > Stopping `now dev` server

    marcio@marcio-Inspiron-5548:~/dados/mozgbrasil/zeit-now/python$ pip3 install --target . --upgrade werkzeug
    Collecting werkzeug
      Using cached https://files.pythonhosted.org/packages/9f/57/92a497e38161ce40606c27a86759c6b92dd34fcdb33f64171ec559257c02/Werkzeug-0.15.4-py2.py3-none-any.whl
    Installing collected packages: werkzeug
    Exception:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
        prefix=options.prefix_path,
      File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
        **kwargs
      File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
        self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
      File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
        isolated=self.isolated,
      File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
        prefix=prefix,
      File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
        i.finalize_options()
      File "/usr/lib/python3.6/distutils/command/install.py", line 274, in finalize_options
        raise DistutilsOptionError("can't combine user with prefix, "
    distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base

--

**Comment by msweeneydev** [comment]
Hello @mozgbrasil, this repository is not intended to be run all at once as a monorepo, this is probably why you were running into issues. You can initialize and run any of the examples using the `now init` command, please let us know if we can help further!

**Comment by mozgbrasil** [comment]
@msweeneydev 

Good morning and thank you my brother
