### ISSUE TITLE
php-7 example does not work with `now dev`

### ISSUE THREAD

**Issue by stephensauceda** [zeit/now-examples#425]
1. Ran `now init` and chose `php-7`.
2. `cd php-7`
3. `now dev`
4. visit `localhost:3000`

expected: A page echo-ing "Hello from PHP on Now 2.0!"

actual:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/1017723/61497043-4171bf80-a98c-11e9-93e9-73b9e43c9a7f.png">

<details>
<summary>Console output</summary>

```
{ Error: spawn ./php-fpm ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn ./php-fpm',
  path: './php-fpm',
  spawnargs: [ '-c', 'php.ini', '--fpm-config', 'php-fpm.ini', '--nodaemonize' ] }
LambdaError: RequestId: 9b22970b-af4f-4a8e-ba3f-69d322147255 Process exited before completing request
    at Lambda.<anonymous> (/snapshot/repo/dist/index.js:1:2571728)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/repo/dist/index.js:1:2569869)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
</details>

NOTE: the example deploys to `now` as expected. It simply doesn't work with `now dev`

**Comment by timothyis** [comment]
Hi @stephensauceda, apologies for the delay in response here. I've just opened an issue for this in the `now-builders` repository so we can start looking into how to support PHP. https://github.com/zeit/now-builders/issues/814
