### ISSUE TITLE
Issue with deploying a Jekyll blog

### ISSUE THREAD

**Issue by RichardLindsay** [zeit/now-examples#494]
I updated my Jekyll blog with the example `package.json`.

```
{
  "private": true,
  "scripts": {
    "build": "jekyll build && mv _site public"
  }
}
```
but receive the following error:

```
2019-09-15T22:13:38.987Z  installing build runtime...
2019-09-15T22:13:38.993Z  yarn info @now/build-utils@latest...
2019-09-15T22:13:38.998Z  yarn info @now/static-build...
2019-09-15T22:13:40.062Z  build runtime installed: 1075.255ms
2019-09-15T22:13:40.651Z  obtaining caches...
2019-09-15T22:13:41.550Z  running builder.exports.build...
2019-09-15T22:13:41.551Z  Downloading user files...
2019-09-15T22:13:41.558Z  installing to /tmp/732c4cf8
2019-09-15T22:13:42.095Z  yarn install v1.17.3
2019-09-15T22:13:42.132Z  info No lockfile found.
2019-09-15T22:13:42.142Z  [1/4] Resolving packages...
2019-09-15T22:13:42.144Z  [2/4] Fetching packages...
2019-09-15T22:13:42.146Z  [3/4] Linking dependencies...
2019-09-15T22:13:42.155Z  [4/4] Building fresh packages...
2019-09-15T22:13:42.161Z  success Saved lockfile.
2019-09-15T22:13:42.168Z  Done in 0.08s.
2019-09-15T22:13:42.179Z  Running "build" script in "package.json"
2019-09-15T22:13:42.180Z  running "yarn run build"
2019-09-15T22:13:42.462Z  yarn run v1.17.3
2019-09-15T22:13:42.505Z  $ jekyll build && mv _site public
2019-09-15T22:13:42.522Z  /bin/sh: jekyll: command not found
2019-09-15T22:13:42.536Z  error Command failed with exit code 127.
2019-09-15T22:13:42.536Z  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2019-09-15T22:13:42.547Z  Error: Exited with 127
2019-09-15T22:13:42.547Z      at ChildProcess.child.on (/tmp/41d02aa0e2a0c97f/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:23427:24)
2019-09-15T22:13:42.547Z      at emitTwo (events.js:126:13)
2019-09-15T22:13:42.547Z      at ChildProcess.emit (events.js:214:7)
2019-09-15T22:13:42.547Z      at maybeClose (internal/child_process.js:925:16)
2019-09-15T22:13:42.547Z      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2019-09-15T22:13:42.620Z  worker exited with code 20 and signal null
2019-09-15T22:13:42.628Z  done
2019-09-15T22:13:45.152Z  done
```

The blog runs fine locally.

Any help would be great.

Thanks

**Comment by ilearnbydoing** [comment]
I am facing similar issue any help would be great.

**Comment by msweeneydev** [comment]
Hey @RichardLindsay @ilearnbydoing, I'm sorry you're facing these issues. I'm looking into this for you both now.

Could you both confirm how you are creating the project?

**Comment by ilearnbydoing** [comment]
I used example Jekyll starter template from Zeit

**Comment by msweeneydev** [comment]
Question again for the both of you, do you have a Gemfile with the Jekyll dependency?

**Comment by RichardLindsay** [comment]
Using 16.2.0

The example I gave was trying to deploy a Jekyll blog that had been generated using the Jekyll Now project. I have since tried to deploy a Jekyll site that was created using the native Jekyll scaffolder which has resulted in the same error.

**Comment by ilearnbydoing** [comment]
Using https://github.com/zeit/now-examples/blob/master/jekyll/Gemfile

only

**Comment by msweeneydev** [comment]
@ilearnbydoing that's very strange, I've not been able to reproduce the issue yet. Could you provide me with a deployment URL so I can look further please?

**Comment by ilearnbydoing** [comment]
@msweeneydev https://zeit.co/ilearnbydoing/jekyll-zeit-demo/g3jyyrz0x?redirect=1 here it is.

**Comment by ilearnbydoing** [comment]
> https://zeit.co/ilearnbydoing/jekyll-zeit-demo/g3jyyrz0x?redirect=1

full logs

installing build runtime...
build runtime installed: 1156.634ms
obtaining caches...
installing to /tmp/218959b1
yarn install v1.17.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.07s.
running "yarn run build"
yarn run v1.17.3
$ jekyll build && mv _site public
/bin/sh: jekyll: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Exited with 127
    at ChildProcess.child.on (/tmp/41d02aa0e2a0c97f/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:23427:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
worker exited with code 20 and signal null
done
done

**Comment by RichardLindsay** [comment]
I forgot to add that I am using the default Gemfile

```
source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 3.8.6"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0", :install_if => Gem.win_platform?
```

My deployment URL is `https://zeit.co/richardlindsay/richardlindsay2019/jvn7bp67h?redirect=1`

**Comment by msweeneydev** [comment]
Thanks @RichardLindsay @ilearnbydoing, investigating currently, will have an update for you as soon as possible.

**Comment by RichardLindsay** [comment]
No problem. Appreciate you looking into it so quickly 👍

**Comment by msweeneydev** [comment]
@RichardLindsay @ilearnbydoing, @styfle just confirmed that this method is only available on canary, you can access this with `npm i -g now@canary`.

I will update the `README.md` file to explicitly state this, however it should be available on stable very shortly. Apologies for the issues and please let me know how you get on 👍

**Comment by RichardLindsay** [comment]
@msweeneydev The Canary build worked perfectly. Thanks again for looking into the issue and keeping us updated.

**Comment by styfle** [comment]
We released stable version and I confirmed that the [one-click jekyll deployment](https://zeit.co/new/jekyll) feature is working.

Thanks!
