### ISSUE TITLE
Go date time is not coming up with an error

### ISSUE THREAD

**Issue by edineu** [zeit/now-examples#499]
Does anyone knows why this is coming up with an error:

![image](https://user-images.githubusercontent.com/5111209/65683936-ce0cbe00-e05e-11e9-9530-e2a6f169c263.png)

Need help to get the timer to show properly.

**Comment by mcsdevv** [comment]
Hey @edineu, thanks for raising the issue, I'm sorry this isn't working for you. This looks like the output when using the port CRA is running on. If you use the port that `now dev` runs on, it will work. Just be aware that it might take a little longer the first time as it must build the Go Serverless Function.

Let me know how you get on!

**Comment by edineu** [comment]
Hey @msweeneydev thank you writing back. I used `now dev` and I got the following:

`$ now dev
> Now CLI 16.2.0 dev (beta) — https://zeit.co/feedback/dev
> Creating initial build
| Preparing package.json for build: Done in 6.70s.> Building @now/static-build@latest:package.json
- Preparing package.json for build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.yarn run v1.17.3
\ Preparing package.json for build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.$ BROWSER=none react-scripts start
/ Preparing package.json for build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.'BROWSER' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Downloading user files...
Detected Create React App framework. Optimizing your deployment...
Create React App does not require a specific Node.js version. Continuing ...
installing to C:\Users\Ed Hansen\Documents\job_project_nord_sense\github-issue-manager-app
yarn install v1.17.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 6.70s.
yarn run v1.17.3
$ BROWSER=none react-scripts start
'BROWSER' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> Error! Failed to detect a server running on port 60202.
Details: https://err.sh/zeit/now/now-static-build-failed-to-detect-a-server`

What could that be

Again thanks for the help.

**Comment by mcsdevv** [comment]
What OS are you using @edineu ?

**Comment by edineu** [comment]
I am using windos 10!

**Comment by mcsdevv** [comment]
Thanks for letting me know, I'm testing this on Windows 10 now!

As a workaround, you can remove the `BROWSER=none` part from the script and select the host provided by `now dev` (likely 3000).

**Comment by edineu** [comment]
I have removed it:

`"scripts": {
    "dev": "react-scripts start",
    "start": "yarn react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },`

, but not sure what to do next in regard to the host provided?

The problem still persist:

`
![image](https://user-images.githubusercontent.com/5111209/65692184-695b5e80-e072-11e9-9a10-909c41751190.png)

`

**Comment by edineu** [comment]
While trying to publish got this error do you think this has anything to do with what we are trying to do:

![image](https://user-images.githubusercontent.com/5111209/65694335-fbb13180-e075-11e9-9100-2dfba82ec21c.png)

**Comment by mcsdevv** [comment]
Hey @edineu, thanks for posting more information on this. It looks like there are currently some issues with Windows 10 for `now dev`, we will investigate these.

The image you've shared, is that from your terminal or the ZEIT Dashboard?

**Comment by edineu** [comment]
Hey @msweeneydev,
That is correct the error msg is coming directly from ZEIT dashboard.

**Comment by mcsdevv** [comment]
Thanks for confirming @edineu, that's really odd, I can't reproduce it on a deployment either. Can you let me know the deployment URL so I can take a closer look? You can email support@zeit.co if you prefer!

We are still investigating the issue with `now dev`.

**Comment by kioltk** [comment]
Hey,

Trying the same example. Succeeded with running fronted by removing BROWSER=none, however the api still reproduce some exceptions. 

When opening localhost:3000/api/date there is http response:
```
Command failed: C:\Users\David\AppData\Local\co.zeit.now\Cache\dev\builders\node_modules\@now\go\dist\analyze -modpath= D:\Downloads\now-examples-master\create-react-app-functions\api\date.go
'C:\Users\David\AppData\Local\co.zeit.now\Cache\dev\builders\node_modules\@now\go\dist\analyze' is not recognized as an internal or external command,
operable program or batch file.
```
And here is the my terminal log:
```
> GET /api/date
> Building @now/go@latest:api/date.go
Failed to parse AST for "api/date.go"
Error: Command failed: C:\Users\David\AppData\Local\co.zeit.now\Cache\dev\builders\node_modules\@now\go\dist\analyze -modpath= D:\Downloads\now-examples-master\create-react-app-functions\api\date.go
'C:\Users\David\AppData\Local\co.zeit.now\Cache\dev\builders\node_modules\@now\go\dist\analyze' is not recognized as an internal or external command,
operable program or batch file.


    at makeError (C:\Users\David\AppData\Local\co.zeit.now\Cache\dev\builders\node_modules\@now\go\dist\index.js:37827:9)
    at C:\Users\David\AppData\Local\co.zeit.now\Cache\dev\builders\node_modules\@now\go\dist\index.js:37931:16
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Object.getAnalyzedEntrypoint (C:\Users\David\AppData\Local\co.zeit.now\Cache\dev\builders\node_modules\@now\go\dist\index.js:4447:22)
    at async Object.build (C:\Users\David\AppData\Local\co.zeit.now\Cache\dev\builders\node_modules\@now\go\dist\index.js:36763:20)
    at async processMessage (C:\Users\David\AppData\Local\co.zeit.now\Cache\dev\builders\builder.js:39:18) {
  message: 'Command failed: C:\\Users\\David\\AppData\\Local\\co.zeit.now\\Cache\\dev\\builders\\node_modules\\@now\\go\\dist\\analyze -modpath= D:\\Downloads\\now-examples-master\\create-react-app-functions\\api\\date.go\n' +
    "'C:\\Users\\David\\AppData\\Local\\co.zeit.now\\Cache\\dev\\builders\\node_modules\\@now\\go\\dist\\analyze' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n' +
    '\n',
  code: 1,
  stdout: '',
  stderr: "'C:\\Users\\David\\AppData\\Local\\co.zeit.now\\Cache\\dev\\builders\\node_modules\\@now\\go\\dist\\analyze' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n',
  failed: true,
  signal: null,
  cmd: 'C:\\Users\\David\\AppData\\Local\\co.zeit.now\\Cache\\dev\\builders\\node_modules\\@now\\go\\dist\\analyze -modpath= D:\\Downloads\\now-examples-master\\create-react-app-functions\\api\\date.go',
  timedOut: false,
  killed: false
}
```

Running on windows 10, now 16.2, go 1.13.

UPD: Seems like you have to create `analyze.bat` or other executable file for windows. 

UPD 2: I also running from Cmder. Will try to run on ubuntu subsystem, so maybe this executable will run properly.

UPD 3: Works fine on ubuntu subsystem.

**Comment by hugmouse** [comment]
Same problem. The errors are identical to those written above

Windows 10 1903: `18950.1000`
Now: `16.3.1`
Go:  `go1.13.1 windows/amd64`

Works well on WSL in Kali Linux.

Kernel: `4.4.0-18950-Microsoft`
Now: `16.3.1`
Go: `go1.12.10 linux/amd64`
